# Copyright (c) Huawei Technologies Co., Ltd. 2022. All rights reserved.

# Basic config
[base]
name = "yolox_post" # The FlowUnit name
device = "cpu" # The device the flowunit runs on，cpu，cuda，ascend。
version = "1.0.0" # The version of the flowunit
description = "description" # The description of the flowunit
entry = "yolox_post@yolox_postFlowUnit" # Python flowunit entry function
type = "python" # Fixed value
group_type = "Generic"  # flowunit group attribution, change as Input/Output/Image/Generic ...

# Flowunit Type
stream = false # Whether the flowunit is a stream flowunit
condition  = false # Whether the flowunit is a condition flowunit
collapse = false # Whether the flowunit is a collapse flowunit
collapse_all = false # Whether the flowunit will collapse all the data
expand = false #  Whether the flowunit is a expand flowunit

[config]
net_h = 288
net_w = 512
num_classes = 80
strides = ['8', '16', '32']
conf_threshold = 0.3
iou_threshold = 0.4

[input]
[input.input1]
name = "in_feat"
type = "float"

[output]
[output.output1]
name = "out_data"
type = "string"
